# This is a basic workflow to help you get started with Actions

name: update and uri

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # Runs every 5 minutes.
  # Runs at 00:00 UTC every day.
  # Actions schedules run at most every 5 minutes.
  schedule:
    # - cron: '*/5 * * * *'
    - cron: '15 0 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: 迁出代码
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      # Runs a single command using the runners shell
      - name: Run install curl git and unar
        run: |
          sudo apt update
          sudo apt-get -y install curl git unar neofetch
          neofetch

      # Runs a set of commands using the runners shell
      - name: Run autoupdate.sh shell script
        run: |
          chmod u+x autoupdate.sh geturi.sh
          bash autoupdate.sh
          bash geturi.sh

      - name: 'Get Date'
        run: |
          echo "REPORT_DATE=$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')" >> $GITHUB_ENV

      - name: 提交更改
        run: |                 
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull origin master
          git add .
          git commit -m "${{env.REPORT_DATE}} 提交"
          git pull --rebase
          
      - name: 推送更改
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          branch: master
          
